print ("Sibenice")
slovo = str(input("Jsem zadej slova: "))
print(slovo)
print("+------+")
print("|      |")
print("|      O")
print("|     -|-")
print("|     / \ ")
print("|")
print("==============")
