print ("Sibenice")
slovo = str(input("Jsem zadej slovo: "))
print(slovo)
print("+------+")
print("|      |")
print("|      O")
print("|     -|-")
print("|     / \ ")
print("|")
print("BOZO😂👌")
print("==============")
